version: '3.8'

services:
  frontend:
    image: twelvelabs-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
  backend:
    image: twelvelabs-backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

networks:
  default:
    driver: bridge